### ISSUE TITLE
docs up to date ?

### ISSUE THREAD

**Issue by Finebouche** [JetBrains-Research/bcnnm-organoids#2]
Hi again,

When trying to follow the steps in  RUN_YOUR_CONFIGURATION.md I encounter several problems : 

1. I don't have a `model` directory
2. I don't have a `SimulationModel-all.jar` file 

I am not a Java programmer so it might be that I am completely out of touch here.

**Comment by human-research** [comment]
Hello, @Finebouche. 

My name is Georgy Galumov and I'm responsible for maintenance of this repository. 

As mentioned in the original paper, 
```
The binary of the model, running scripts and readme files can be found at https://github.com/JetBrains-Research/bcnnm-organoids/raw/master/public/fncom.2020.588224.zip.
```

Please, use the link [https://github.com/JetBrains-Research/bcnnm-organoids/raw/master/public/fncom.2020.588224.zip](https://github.com/JetBrains-Research/bcnnm-organoids/raw/master/public/fncom.2020.588224.zip) to download the packed model for your experiments. 

After downloading the archive, please use instructions from the `RUN_YOUR_CONFIGURATION.md` manual.

To correct any possible misunderstanding, I will update the user manual.  Thank you for your feedback. 

I must say that our team greatly improved the framework. The model from this repository is discontinued and will not support in future.

If you want to do computational experiments using our platform, let's discuss this after January 10, 2022. 

You can reach our team by email `info@bcnnm.net`. 

Thanks again and have a nice day!

**Comment by Finebouche** [comment]
Hello,
Thank you for your answer, I am really interrested in any improvment to the framework. 

I will contact you by email after the 10th then 👍
